variables:
  CI_PROJECT_DIR: /var/www/flaviuscojocariu.com/personal-website
  # GIT_CLONE_PATH: /var/www/flaviuscojocariu.com/personal-website
stages:
  - deploy
deploy:
  stage: deploy
  only:
    - master
  script:
    - python3 -m pip install virtualenv
    - virtualenv env
    - source env/bin/activate
    - python3 -m pip install -r requirements.txt
    - npm install
    - python3 ssg.py  

