stages:
  - deploy
deploy:
  stage: deploy
  variables:
    TARGET_DIR: /var/www/flaviuscojocariu.com/personal-website
  only:
    - master
  script:
    - source env/bin/activate
    - python -m pip install -r requirements.txt
    - npm install
    - python3 ssg.py  

