stages:
  - deploy
deploy:
  stage: deploy
  script:
    - cat generated-bash-script | su --shell /bin/bash --login admin
    - source env/bin/activate
    - python -m pip install -r requirements.txt
    - npm install
    - python3 ssg.py  

